/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as ApiGibsKeyRouteImport } from './routes/api/gibs-key'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogAssRouteImport } from './routes/blog/ass'
import { Route as BlogOopsWeDidItAgainRouteImport } from './routes/blog/oops-we-did-it-again'
import { Route as BlogWeRichLmaoRouteImport } from './routes/blog/we-rich-lmao'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as StatusIndexRouteImport } from './routes/status/index'
import { Route as StatusIncidentReportApril12026ControlPlaneDegradationRouteImport } from './routes/status/incident-report-april-1-2026-control-plane-degradation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGibsKeyRoute = ApiGibsKeyRouteImport.update({
  id: '/api/gibs-key',
  path: '/api/gibs-key',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogAssRoute = BlogAssRouteImport.update({
  id: '/ass',
  path: '/ass',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogOopsWeDidItAgainRoute = BlogOopsWeDidItAgainRouteImport.update({
  id: '/oops-we-did-it-again',
  path: '/oops-we-did-it-again',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogWeRichLmaoRoute = BlogWeRichLmaoRouteImport.update({
  id: '/we-rich-lmao',
  path: '/we-rich-lmao',
  getParentRoute: () => BlogRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/status/',
  path: '/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIncidentReportApril12026ControlPlaneDegradationRoute =
  StatusIncidentReportApril12026ControlPlaneDegradationRouteImport.update({
    id: '/status/incident-report-april-1-2026-control-plane-degradation',
    path: '/status/incident-report-april-1-2026-control-plane-degradation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/404': typeof R404Route
  '/api/gibs-key': typeof ApiGibsKeyRoute
  '/blog/ass': typeof BlogAssRoute
  '/blog/oops-we-did-it-again': typeof BlogOopsWeDidItAgainRoute
  '/blog/we-rich-lmao': typeof BlogWeRichLmaoRoute
  '/status/incident-report-april-1-2026-control-plane-degradation': typeof StatusIncidentReportApril12026ControlPlaneDegradationRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/status/': typeof StatusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/api/gibs-key': typeof ApiGibsKeyRoute
  '/blog/ass': typeof BlogAssRoute
  '/blog/oops-we-did-it-again': typeof BlogOopsWeDidItAgainRoute
  '/blog/we-rich-lmao': typeof BlogWeRichLmaoRoute
  '/status/incident-report-april-1-2026-control-plane-degradation': typeof StatusIncidentReportApril12026ControlPlaneDegradationRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/status': typeof StatusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/404': typeof R404Route
  '/api/gibs-key': typeof ApiGibsKeyRoute
  '/blog/ass': typeof BlogAssRoute
  '/blog/oops-we-did-it-again': typeof BlogOopsWeDidItAgainRoute
  '/blog/we-rich-lmao': typeof BlogWeRichLmaoRoute
  '/status/incident-report-april-1-2026-control-plane-degradation': typeof StatusIncidentReportApril12026ControlPlaneDegradationRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/status/': typeof StatusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/docs'
    | '/404'
    | '/api/gibs-key'
    | '/blog/ass'
    | '/blog/oops-we-did-it-again'
    | '/blog/we-rich-lmao'
    | '/status/incident-report-april-1-2026-control-plane-degradation'
    | '/blog/'
    | '/docs/'
    | '/status/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/api/gibs-key'
    | '/blog/ass'
    | '/blog/oops-we-did-it-again'
    | '/blog/we-rich-lmao'
    | '/status/incident-report-april-1-2026-control-plane-degradation'
    | '/blog'
    | '/docs'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/docs'
    | '/404'
    | '/api/gibs-key'
    | '/blog/ass'
    | '/blog/oops-we-did-it-again'
    | '/blog/we-rich-lmao'
    | '/status/incident-report-april-1-2026-control-plane-degradation'
    | '/blog/'
    | '/docs/'
    | '/status/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  R404Route: typeof R404Route
  ApiGibsKeyRoute: typeof ApiGibsKeyRoute
  StatusIncidentReportApril12026ControlPlaneDegradationRoute: typeof StatusIncidentReportApril12026ControlPlaneDegradationRoute
  StatusIndexRoute: typeof StatusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gibs-key': {
      id: '/api/gibs-key'
      path: '/api/gibs-key'
      fullPath: '/api/gibs-key'
      preLoaderRoute: typeof ApiGibsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/ass': {
      id: '/blog/ass'
      path: '/ass'
      fullPath: '/blog/ass'
      preLoaderRoute: typeof BlogAssRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/oops-we-did-it-again': {
      id: '/blog/oops-we-did-it-again'
      path: '/oops-we-did-it-again'
      fullPath: '/blog/oops-we-did-it-again'
      preLoaderRoute: typeof BlogOopsWeDidItAgainRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/we-rich-lmao': {
      id: '/blog/we-rich-lmao'
      path: '/we-rich-lmao'
      fullPath: '/blog/we-rich-lmao'
      preLoaderRoute: typeof BlogWeRichLmaoRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/status/': {
      id: '/status/'
      path: '/status'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/incident-report-april-1-2026-control-plane-degradation': {
      id: '/status/incident-report-april-1-2026-control-plane-degradation'
      path: '/status/incident-report-april-1-2026-control-plane-degradation'
      fullPath: '/status/incident-report-april-1-2026-control-plane-degradation'
      preLoaderRoute: typeof StatusIncidentReportApril12026ControlPlaneDegradationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteRouteChildren {
  BlogAssRoute: typeof BlogAssRoute
  BlogOopsWeDidItAgainRoute: typeof BlogOopsWeDidItAgainRoute
  BlogWeRichLmaoRoute: typeof BlogWeRichLmaoRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogAssRoute: BlogAssRoute,
  BlogOopsWeDidItAgainRoute: BlogOopsWeDidItAgainRoute,
  BlogWeRichLmaoRoute: BlogWeRichLmaoRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  R404Route: R404Route,
  ApiGibsKeyRoute: ApiGibsKeyRoute,
  StatusIncidentReportApril12026ControlPlaneDegradationRoute:
    StatusIncidentReportApril12026ControlPlaneDegradationRoute,
  StatusIndexRoute: StatusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
