{{- if .Values.deployment }}
{{- with .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .metadata.name }}
  labels:
    app: {{ .metadata.name }}
spec:
  replicas: {{ .spec.replicas }}
  selector:
    matchLabels:
      app: {{ .metadata.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .spec.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .spec.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      # # Disabled for now. Was using too many resources for my little cluster :3
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "9100"
      labels:
        app: {{ .metadata.name }}
    spec:
      terminationGracePeriodSeconds: {{ .spec.template.spec.terminationGracePeriodSeconds }}
      containers:
        {{- range .spec.template.spec.containers }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: Always
          ports:
            # - name: metrics
            #   containerPort: {{ .port }}
            - name: http
              containerPort: {{ .port }}
          env:
            # Add the pod name for logging - TODO
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
              # Add any shared secrets
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              {{- if $value.value }}
              value: {{ $value.value | quote }}
              {{- else if $value.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretKeyRef.name | quote }}
                  key: {{ $value.secretKeyRef.key | quote }}
              {{- end }}
            {{- end }}
              # Add application specific secrets
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              {{- if $value.value }}
              value: {{ $value.value | quote }}
              {{- else if $value.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretKeyRef.name | quote }}
                  key: {{ $value.secretKeyRef.key | quote }}
              {{- end }}
            {{- end }}  

            
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command: {{ .lifecycle.preStop.exec.command }}
          readinessProbe:
            httpGet:
              path: {{ .readinessProbe.httpGet.path  }}
              port: {{ .port }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
            timeoutSeconds: 5
            failureThreshold: 3
        {{- end }}
      volumes:
        {{- range .spec.template.spec.volumes }}
        - name: {{ .name }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
          {{- else if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- else if .emptyDir }}
          emptyDir: {}
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}
