{{- if .Values.service }}
{{- with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .metadata.name }}
spec:
  clusterIP: {{ .spec.clusterIP }}
  selector:
    app: {{ .spec.selector.app }}
  ports:
    {{- range .spec.ports }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
{{- end }}
{{- end }}
