# Must start with 'deployments' key
deployments:
  replicas: 3
  name: web
  containers:
    - name: web
      port: 3000
      image: joswayski/averagedatabase:latest
  # Add environment
    env:
      - name: BASE_API_URL
        value: http://api:80
